Repository JECT-Study/JECT-5-FE, pull requests merged in 2025-08, with the labels that each got.

#53 게임 생성 api 연결
  service/app/src/entities/game/api/createGame.ts
  service/app/src/entities/game/api/index.ts
  service/app/src/entities/game/model/gameCreationReducer.ts
  service/app/src/entities/game/model/state/create/actions.ts
  service/app/src/entities/game/model/state/create/reducer.ts
  service/app/src/entities/game/model/state/create/selectors.ts
  service/app/src/entities/game/model/state/create/state.ts
  service/app/src/entities/game/model/state/create/useGameCreation.ts
  service/app/src/entities/game/model/state/create/utils.ts
  service/app/src/entities/game/ui/components/fileUploadArea.tsx
  service/app/src/entities/game/ui/components/questionInputForm.tsx
  service/app/src/entities/game/ui/components/questionList.tsx
  service/app/src/entities/game/ui/popupManager.tsx
  service/app/src/entities/game/utils/gameSave.ts
  service/app/src/entities/game/utils/index.ts
  service/app/src/entities/game/utils/s3Upload.ts
  shared/lib/fetchClient.ts
Labels: ✨feature, 👩🏻‍💻frontend

#56 gamecard 컴포넌트 생성
  shared/design/src/components/gameCard/index.tsx
  shared/design/src/stories/gameCard.stories.tsx
Labels: ✨feature

#47 게임 생성 폼 상태관리 추가
  service/app/public/checker.svg
  service/app/src/app/create/page.tsx
  service/app/src/entities/game/api/createGame.ts
  service/app/src/entities/game/api/index.ts
  service/app/src/entities/game/model/index.ts
  service/app/src/entities/game/model/state/create/actions.ts
  service/app/src/entities/game/model/state/create/gameCreationContext.tsx
  service/app/src/entities/game/model/state/create/index.ts
  service/app/src/entities/game/model/state/create/reducer.ts
  service/app/src/entities/game/model/state/create/selectors.ts
  service/app/src/entities/game/model/state/create/state.ts
  service/app/src/entities/game/model/state/create/useGameCreation.ts
  service/app/src/entities/game/model/state/create/utils.ts
  service/app/src/entities/game/model/state/index.ts
  service/app/src/entities/game/ui/components/createGameNavigation.tsx
  service/app/src/entities/game/ui/components/fileUploadArea.tsx
  service/app/src/entities/game/ui/components/questionInputForm.tsx
  service/app/src/entities/game/ui/components/questionList.tsx
  service/app/src/entities/game/ui/popupManager.tsx
  service/app/src/entities/game/utils/__tests__/fileValidation.test.ts
  service/app/src/entities/game/utils/fileValidation.ts
  service/app/src/entities/game/utils/gameSave.ts
  service/app/src/entities/game/utils/index.ts
  service/app/src/entities/game/utils/s3Upload.ts
  shared/design/src/components/question/index.tsx
  shared/lib/fetchClient.ts
Labels: ✨feature, 👩🏻‍💻frontend

#61 추가 팝업 구현
  service/app/src/entities/game/model/state/create/actions.ts
  service/app/src/entities/game/model/state/create/state.ts
  service/app/src/entities/game/model/state/create/utils.ts
  service/app/src/entities/game/model/useGamePopupActions.tsx
  service/app/src/entities/game/ui/components/fileUploadArea.tsx
  service/app/src/entities/game/ui/components/questionInputForm.tsx
  service/app/src/entities/game/ui/interactions/saveButton.tsx
  shared/design/public/checker.svg
  shared/design/src/components/question/index.tsx
Labels: ✨feature

#62 gameCreate 공통컴포넌트 생성
  service/app/public/create-game-icon.svg
  shared/design/public/create-game-icon.svg
  shared/design/src/components/gameCreate/index.tsx
  shared/design/src/stories/gameCreate.stories.tsx
Labels: ✨feature, 👩🏻‍💻frontend

#73 library 페이지 라우팅 및 레이아웃 구성
  service/app/public/character-quiz-thumbnail.svg
  service/app/public/emoji-proverb-thumbnail.svg
  service/app/public/famous-quote-thumbnail.svg
  service/app/public/word-relay-thumbnail.svg
  service/app/src/app/games/components/GameLibraryGrid.tsx
  service/app/src/app/games/page.tsx
Labels: ✨feature, 👩🏻‍💻frontend

#80 게임 진행페이지 개발
  .cursor/mcp.json
  service/app/next.config.mjs
  service/app/src/app/game/[gameId]/components/dialogs/exitConfirmDialog.tsx
  service/app/src/app/game/[gameId]/layout.tsx
  service/app/src/app/game/[gameId]/play/layout.tsx
  service/app/src/app/game/[gameId]/play/page.tsx
  service/app/src/app/game/[gameId]/result/page.tsx
  service/app/src/app/game/[gameId]/setup/components/gameSetup.tsx
  service/app/src/app/game/[gameId]/setup/page.tsx
  service/app/src/app/game/[gameId]/store/useGameStore.tsx
  shared/design/src/components/dialog/index.tsx
Labels: ✨feature

#99 게임 생성 페이지 overlay 버그 수정
  service/app/src/app/create/page.tsx
  service/app/src/app/dashboard/page.tsx
  service/app/src/entities/game/api/getMyGames.ts
  service/app/src/entities/game/api/index.ts
  service/app/src/entities/game/model/useGamePopupActions.tsx
  service/app/src/entities/game/model/useInfiniteMyGames.ts
  service/app/src/entities/game/ui/interactions/registerButton.tsx
  service/app/src/entities/game/ui/interactions/saveButton.tsx
  service/app/src/mocks/handlers/game.ts
Labels: ✨feature, 🐛bug, 👩🏻‍💻frontend

#114 favicon 추가
  service/app/public/favicon.svg
  service/app/src/app/layout.tsx
Labels: ✨feature, 👩🏻‍💻frontend

#124 홈페이지 테스트 코드 작성 및 버그 수정
  service/app/public/kakao-logo.svg
  service/app/src/app/__tests__/home-e2e-scenarios.md
  service/app/src/app/__tests__/home.spec.ts
  service/app/src/app/games/page.tsx
  service/app/src/app/layout.tsx
  service/app/src/app/login/kakao/callback/page.tsx
  service/app/src/app/login/kakao/page.tsx
  service/app/src/app/login/page.tsx
  service/app/src/entities/auth/hooks/useAuth.ts
  service/app/src/entities/auth/utils/__tests__/sessionValidator.test.ts
  service/app/src/entities/auth/utils/cookieUtils.ts
  service/app/src/entities/auth/utils/sessionValidator.ts
  service/app/src/entities/game/model/state/create/gameCreationContext.tsx
  service/app/src/entities/game/ui/components/gamePreview.tsx
  service/app/src/entities/game/ui/interactions/saveButton.tsx
  service/app/src/mocks/__tests__/authHandlers.test.ts
  service/app/src/mocks/__tests__/gameHandlers.test.ts
  service/app/src/mocks/__tests__/setup.ts
  service/app/src/mocks/browser.ts
  service/app/src/mocks/handlers/auth.ts
  service/app/src/mocks/handlers/game.ts
  service/app/src/mocks/index.ts
  service/app/src/mocks/mswComponent.tsx
  service/app/src/mocks/mswProvider.tsx
  service/app/src/mocks/utils/gameHandlers.ts
  service/app/src/widgets/GameSection.tsx
  service/app/src/widgets/HeroSection.tsx
  service/app/src/widgets/HomeNavigation.tsx
  shared/design/src/components/gameCard/index.tsx
  shared/lib/fetchClient.ts
Labels: ✨feature, 🐛bug, 👩🏻‍💻frontend

#131 대시보드 페이지 테스트 코드 작성 및 버그 수정
  service/app/src/app/__tests__/home.spec.ts
  service/app/src/app/dashboard/__tests__/dashboard-test-scenarios.md
  service/app/src/app/dashboard/__tests__/dashboard.spec.ts
  service/app/src/app/dashboard/page.tsx
  service/app/src/entities/auth/hooks/useAuth.ts
  service/app/src/entities/game/model/useDashboardPopupActions.tsx
  service/app/src/entities/game/ui/components/gamePreview.tsx
  service/app/src/mocks/data/common.ts
  service/app/src/mocks/handlers/auth.ts
  service/app/src/mocks/utils/mockGenerators.ts
  shared/design/src/components/dialog/index.tsx
  shared/design/src/components/gameCard/index.tsx
Labels: ✨feature, 🐛bug, 👩🏻‍💻frontend

#137 세션 쿠키 검증 시점 조절
  service/app/src/entities/auth/hooks/useAuth.ts
Labels: 🐛bug

#160 playwright cache
  .github/workflows/ci.yml
  service/app/next.config.mjs
  service/app/package.json
  service/app/playwright.config.ts
  service/app/scripts/playwright.ts
  service/app/src/app/dashboard/__tests__/dashboard.spec.ts
  service/app/src/app/game/[gameId]/play/components/gamePlayContent.tsx
  service/app/src/app/game/[gameId]/play/components/gamePlayNavigation.tsx
  service/app/src/mocks/mswProvider.tsx
  service/app/tsconfig.json
  yarn.lock
Labels: ⚙️chore

#167 Dialog 컴포넌트 리팩토링
  service/app/src/app/game/[gameId]/components/dialogs/exitConfirmDialog.tsx
  service/app/src/entities/game/model/useDashboardPopupActions.tsx
  service/app/src/entities/game/model/useGamePopupActions.tsx
  service/app/src/entities/game/ui/components/gamePreview.tsx
  shared/design/index.css
  shared/design/src/components/dialog/customDialog.tsx
  shared/design/src/components/dialog/dialog.css
  shared/design/src/components/dialog/index.tsx
  shared/design/src/stories/dialog.stories.tsx
  yarn.lock
Labels: ✨feature, 🪄refactor
