Repository JECT-Study/JECT-5-FE, pull requests merged in 2025-07, with the labels that each got.

#16 피그마 플러그인 제작
  .gitignore
  .yarnrc.yml
  shared/figma-plugin/README.md
  shared/figma-plugin/eslint.config.mjs
  shared/figma-plugin/index.html
  shared/figma-plugin/package.json
  shared/figma-plugin/src/App.css
  shared/figma-plugin/src/App.tsx
  shared/figma-plugin/src/main.ts
  shared/figma-plugin/src/server.ts
  shared/figma-plugin/src/socket.ts
  shared/figma-plugin/src/ui.tsx
  shared/figma-plugin/src/utils/node.ts
  shared/figma-plugin/tsconfig.json
  shared/figma-plugin/tsup.config.js
  shared/figma-plugin/vite.config.js
  yarn.lock
Labels: ⚙️chore, ✨feature, 📃docs

#18 버튼/아이콘 컴포넌트 구현
  .github/workflows/dev.yml
  .vscode/settings.json
  .yarnrc.yml
  prettier.config.js
  shared/design/eslint.config.mjs
  shared/design/package.json
  shared/design/src/components/button.tsx
  shared/design/src/components/button/baseButton.tsx
  shared/design/src/components/button/destructiveBoxButton.tsx
  shared/design/src/components/button/destructiveSolidIconButton.tsx
  shared/design/src/components/button/primaryBoxButton.tsx
  shared/design/src/components/button/primarySolidIconButton.tsx
  shared/design/src/components/button/secondaryGhostIconButton.tsx
  shared/design/src/components/button/secondaryOutlineBoxButton.tsx
  shared/design/src/components/button/secondaryPlainBoxButton.tsx
  shared/design/src/components/button/secondaryPlainIconButton.tsx
  shared/design/src/icons/add.tsx
  shared/design/src/icons/arrow.tsx
  shared/design/src/icons/cross.tsx
  shared/design/src/icons/edit.tsx
  shared/design/src/icons/hidden.tsx
  shared/design/src/icons/icon.json
  shared/design/src/icons/iconplaceholder_16px.tsx
  shared/design/src/icons/iconplaceholder_24px.tsx
  shared/design/src/icons/iconplaceholder_28px.tsx
  shared/design/src/icons/iconplaceholder_32px.tsx
  shared/design/src/icons/index.ts
  shared/design/src/icons/magnifier.tsx
  shared/design/src/icons/minus.tsx
  shared/design/src/icons/moreDot.tsx
  shared/design/src/icons/more_dot.tsx
  shared/design/src/icons/play.tsx
  shared/design/src/icons/show.tsx
  shared/design/src/icons/sun.tsx
  shared/design/src/icons/trash.tsx
  shared/design/src/icons/unshare.tsx
  shared/design/src/icons/upload.tsx
  shared/design/src/scripts/generateIcon.js
  shared/design/src/stories/button.mdx
  shared/design/src/stories/button.stories.tsx
  shared/design/src/stories/destructiveBoxButton.stories.tsx
  shared/design/src/stories/icon.stories.tsx
  shared/design/src/stories/primaryBoxButton.stories.tsx
  shared/design/src/stories/primarySolidIconButton.stories.tsx
  shared/design/src/stories/secondaryGhostIconButton.stories.tsx
  shared/design/src/stories/secondaryOutlineBoxButton.stories.tsx
  shared/design/src/stories/secondaryPlainBoxButton.stories.tsx
  shared/design/src/stories/secondaryPlainIconButton.stories.tsx
  shared/design/src/tokens/variables.json
  shared/design/src/utils/cn.ts
  shared/design/vitest.config.ts
  shared/eslint/base.js
  yarn.lock
Labels: ⚙️chore, ✨feature

#21 게임 목록 조회 및 검색 API
  service/app/src/entities/game/api/getGameDetail.ts
  service/app/src/entities/game/api/getGameList.ts
  service/app/src/entities/game/index.ts
  service/app/src/entities/game/model/index.ts
  service/app/src/entities/game/model/utils.ts
Labels: ✨feature, 👩🏻‍💻frontend

#23 게임 관련 API 모킹
  service/app/package.json
  service/app/src/entities/game/api/gameDelete.ts
  service/app/src/entities/game/api/gamePlay.ts
  service/app/src/entities/game/api/gameSave.ts
  service/app/src/entities/game/api/gameShare.ts
  service/app/src/entities/game/api/index.ts
  service/app/src/entities/game/api/presignedUrl.ts
  service/app/src/entities/game/utils/fileValidation.ts
  service/app/src/entities/game/utils/index.ts
  service/app/src/entities/game/utils/s3Upload.ts
  service/app/src/mocks/__tests__/gameHandlers.test.ts
  service/app/src/mocks/handlers/game.ts
  service/app/src/mocks/handlers/index.ts
  service/app/src/mocks/utils/gameHandlers.ts
  yarn.lock
Labels: ✨feature, 👩🏻‍💻frontend

#24 api 작성 및 핸들러를 통한 MSW 모킹
  .github/workflows/ci.yml
  package.json
  service/app/package.json
  service/app/public/mockServiceWorker.js
  service/app/src/entities/auth/api/kakaoLogin.ts
  service/app/src/entities/auth/model/auth.ts
  service/app/src/entities/auth/model/authRequest.ts
  service/app/src/entities/game/api/createGame.ts
  service/app/src/entities/game/api/deleteGame.ts
  service/app/src/entities/game/api/getGameDetail.ts
  service/app/src/entities/game/api/getGameList.ts
  service/app/src/entities/game/api/getPresignedUrl.ts
  service/app/src/entities/game/api/index.ts
  service/app/src/entities/game/api/playGame.ts
  service/app/src/entities/game/api/shareGame.ts
  service/app/src/entities/game/api/updateGame.ts
  service/app/src/entities/game/index.ts
  service/app/src/entities/game/model/game.ts
  service/app/src/entities/game/model/gameRequest.ts
  service/app/src/entities/game/model/index.ts
  service/app/src/entities/game/model/utils.ts
  service/app/src/entities/game/utils/__tests__/fileValidation.test.ts
  service/app/src/entities/game/utils/__tests__/s3Upload.test.ts
  service/app/src/entities/game/utils/errorHandlers.ts
  service/app/src/entities/game/utils/fileValidation.ts
  service/app/src/entities/game/utils/index.ts
  service/app/src/entities/game/utils/s3Upload.ts
  service/app/src/entities/game/utils/toQueryString.ts
  service/app/src/mocks/__tests__/authHandlers.test.ts
  service/app/src/mocks/__tests__/gameHandlers.test.ts
  service/app/src/mocks/__tests__/setup.ts
  service/app/src/mocks/data/auth.ts
  service/app/src/mocks/data/common.ts
  service/app/src/mocks/data/game.ts
  service/app/src/mocks/handlers/auth.ts
  service/app/src/mocks/handlers/game.ts
  service/app/src/mocks/handlers/index.ts
  service/app/src/mocks/handlers/user.ts
  service/app/src/mocks/utils/gameHandlers.ts
  service/app/src/mocks/utils/mockGenerators.ts
  service/app/src/mocks/utils/responseHelpers.ts
  service/app/tsconfig.json
  service/app/vitest.config.ts
  service/app/vitest.msw.config.ts
  shared/lib/__tests__/fetchClient.test.ts
  shared/lib/fetchClient.ts
  shared/lib/fetchClientFactory.ts
  shared/types/common.ts
  shared/types/response.ts
  yarn.lock
Labels: ⚙️chore, ✨feature, 👩🏻‍💻frontend

#27 패키지 설치
  service/app/package.json
  service/app/src/app/layout.tsx
  yarn.lock
Labels: ⚙️chore

#29 Question , PlayerStatus, Progress 컴포넌트 구현
  shared/design/src/components/button/destructiveSolidIconButton.tsx
  shared/design/src/components/playerStatus/index.tsx
  shared/design/src/components/progress/index.tsx
  shared/design/src/components/question/index.tsx
  shared/design/src/stories/playerStatus.stories.tsx
  shared/design/src/stories/progress.stories.tsx
  shared/design/src/stories/question.stories.tsx
Labels: ✨feature

#41 게임 생성 레이아웃, 라우팅 추가
  service/app/src/app/create/page.tsx
  service/app/src/entities/game/ui/createGameNavigation.tsx
  service/app/src/entities/game/ui/fileUploadArea.tsx
  service/app/src/entities/game/ui/questionInputForm.tsx
  service/app/src/entities/game/ui/questionList.tsx
  shared/design/src/components/question/index.tsx
  shared/design/src/components/upload/upload.tsx
Labels: ✨feature, 👩🏻‍💻frontend

#43 팝업 ui 시스템 구축 및 ui 컴포넌트 디렉토리 정리
  service/app/src/app/create/page.tsx
  service/app/src/entities/game/model/usePopupManager.ts
  service/app/src/entities/game/ui/components/createGameNavigation.tsx
  service/app/src/entities/game/ui/components/fileUploadArea.tsx
  service/app/src/entities/game/ui/components/index.ts
  service/app/src/entities/game/ui/components/questionInputForm.tsx
  service/app/src/entities/game/ui/components/questionList.tsx
  service/app/src/entities/game/ui/fileUploadArea.tsx
  service/app/src/entities/game/ui/interactions/index.ts
  service/app/src/entities/game/ui/interactions/registerButton.tsx
  service/app/src/entities/game/ui/interactions/saveButton.tsx
  service/app/src/entities/game/ui/popupManager.tsx
  service/app/src/entities/game/ui/popups/fileSizeErrorPopup.tsx
  service/app/src/entities/game/ui/popups/fileTypeErrorPopup.tsx
  service/app/src/entities/game/ui/popups/index.ts
  service/app/src/entities/game/ui/popups/libraryRegisterPopup.tsx
  service/app/src/entities/game/ui/popups/saveConfirmPopup.tsx
Labels: ✨feature, 👩🏻‍💻frontend

#45 참가자 페이지 레이아웃 및 기능 개발
  .cursor/rules/figma/convert.mdc
  service/app/src/app/game/[gameId]/components/index.tsx
  service/app/src/app/game/[gameId]/layout.tsx
  service/app/src/app/game/[gameId]/page.tsx
  service/app/src/app/game/[gameId]/play/page.tsx
  service/app/src/app/game/[gameId]/result/page.tsx
  service/app/src/app/game/[gameId]/setup/page.tsx
  service/app/src/app/game/[gameId]/store/useGameStore.tsx
  service/app/src/mocks/utils/mockGenerators.ts
  shared/design/src/components/input/index.tsx
  shared/design/src/components/playerStatus/index.tsx
Labels: ✨feature
